# Generated by Django 4.2.1 on 2023-05-28 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdukItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_produk", models.CharField(max_length=100)),
                ("harga", models.FloatField()),
                ("harga_diskon", models.FloatField(blank=True, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("deskripsi", models.TextField()),
                ("gambar", models.ImageField(upload_to="product_pics")),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("NEW", "primary"),
                            ("SALE", "info"),
                            ("BEST", "danger"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("S", "Shirt"),
                            ("SW", "Sport wear"),
                            ("OW", "Outwear"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProdukItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordered", models.BooleanField(default=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "produkItem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="toko.produkitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_mulai", models.DateTimeField(auto_now_add=True)),
                ("tanggal_order", models.DateTimeField(blank=True, null=True)),
                ("ordered", models.BooleanField(default=False)),
                ("produkItem", models.ManyToManyField(to="toko.orderprodukitem")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
