# Generated by Django 4.2.1 on 2023-05-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produkitem",
            name="label",
            field=models.CharField(
                choices=[("NEW", "primary"), ("SALE", "secondary"), ("BEST", "danger")],
                max_length=4,
            ),
        ),
    ]
